#! /bin/sh

sxhkd &
/home/sfortas/.screenlayout/layout3.sh
#feh --bg-scale --no-xinerama /home/sfortas/Pictures/wallpaper-orig-1.jpg
feh --bg-fill --no-xinerama /home/sfortas/pix/highway_by_axiomdesign-d9em9fs.jpg
polybar seb_bspwm &

monitors=$(xrandr -q | grep "\<connected\>" | wc -l)

bg=$(xrdb -query | awk '/^\*.background:/ { print $2 }')
brmagenta=$(xrdb -query | awk '/^\*.color13:/ { print $2 }')
brred=$(xrdb -query | awk '/^\*.color9:/ { print $2 }')

bspc monitor DP-7 -n West
bspc monitor DP-4 -n North
bspc monitor DP-5 -n East

bspc monitor West   -d W1 W2 W3
bspc monitor North  -d N1 N2 N3
bspc monitor East   -d E1 E2 E3

bspc config border_width         2
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color  $bg
bspc config active_border_color  $brmagenta
bspc config focused_border_color  $brred
bspc config presel_feedback_color  $bg

bspc config top_padding 10
bspc config bottom_padding 10
bspc config right_padding 7
bspc config left_padding 7

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
