#!/bin/bash
if [[ $# -gt 0 ]]; then
    if [[ "-y" == $1 ]];  then
        no_confirm=1
    fi
fi
        
here=$(readlink -f $(dirname $0))
cd ${here}

function install_vim_packages {
    packages=(
        https://github.com/bling/vim-bufferline
        https://github.com/kien/ctrlp.vim
        https://github.com/vim-airline/vim-airline
        https://github.com/vim-airline/vim-airline-themes
        https://github.com/tpope/vim-fugitive
        https://github.com/lyuts/vim-rtags
    )
    vim=${HOME}/.vim
    bundle=${vim}/bundle
    mkdir -p ${vim}/autoload ${bundle}
    # install pathogen
    if [ ! -f ${vim}/autoload/pathogen.vim ]; then
        cmd="curl -LSso ${vim}/autoload/pathogen.vim https://tpo.pe/pathogen.vim"
        echo "Executing \"${cmd}\""
        eval ${cmd}
    fi

    for package in ${packages[@]}
    do
        name=$(basename ${package})
        dir=${bundle}/${name}
        if [ ! -d ${dir} ]; then
            cmd="git clone ${package} ${dir}"
            echo "Executing: \"${cmd}\""
            eval ${cmd}
        fi
    done
}

function confirm {
    [[ "x${no_confirm}" == "x1" ]] && return 0
    echo -n "$@ [y/N]: "
    read answer && echo "" && return 0
    echo "" && return 1
}

function install_file {
    src=$1
    dst=$2
    test -L ${dst} && rm -f ${dst}
    test -f ${dst} && mv ${dst} ${dst}.bak
    ln -s ${src} ${dst}
}

for file in dot*
do
    real_name=$(echo ${file} | sed -e 's/^dot/./')
    base_name=$(basename ${real_name})
    if [[ -f ${HOME}/${base_name} ]]; then
        confirm "${HOME}/${base_name} already exists and is a file. Overwrite?" && \
            install_file ${here}/${file} ${HOME}/${base_name} 
    elif [[ -L ${HOME}/${base_name} ]]; then
        confirm "${HOME}/${base_name} is already a link. Overwrite?" && \
            install_file ${here}/${file} ${HOME}/${base_name} 
    else
        echo "Creating link ${HOME}/${base_name} to ${real_name}"
        install_file ${here}/${file} ${HOME}/${base_name} 
    fi
    #cp $f $HOME/$real_name
done
test -d $HOME/.oh-my-zsh/ || git clone https://github.com/robbyrussell/oh-my-zsh.git $HOME/.oh-my-zsh
cp *-theme $HOME/.oh-my-zsh/themes/
cp -R vim $HOME/.vim
install_vim_packages

