#! /bin/sh

sxhkd &
# ${HOME}/bin/screenlayout_i3.sh
#${HOME}/bin/screenlayout_2.sh
${HOME}/.screenlayout/layout2.sh
# feh --bg-fill --no-xinerama ${HOME}/pix/casey-horner-1392391-unsplash.jpg 
# feh --bg-fill --no-xinerama /home/sfortas/media/paul-chadeisson-blade-runner-pchadeisson-30-03-v2.jpg
# feh --bg-fill --no-xinerama /home/sfortas/media/paul-chadeisson-mute-pchadeisson-016-conceptart-02.jpg
# feh --bg-fill /home/sfortas/media/paul-chadeisson-blade-runner-pchadeisson-14b-noship.jpg
# feh --bg-fill /home/sfortas/media/paul-chadeisson-blade-runner-pchadeisson-14c.jpg
# feh --bg-fill /home/sfortas/media/paul-chadeisson-mute-pchadeisson-016-conceptart-02.jpg
#feh --bg-fill --no-xinerama /home/sfortas/pix/vxlj6hsqcbl71.jpg
#feh --bg-fill --no-xinerama /home/sfortas/pix/mountains_clouds_landscapes_nature_trees_rocks_Canada_Alberta_lakes_Lake_Luise_3840x2400.jpg
#feh --bg-fill --no-xinerama /home/sfortas/pix/backgrounds/kootney_bc.jpg
# feh --bg-fill --no-xinerama /home/sfortas/pix/backgrounds/background-climb-cold-1054164.jpg
feh --bg-fill --no-xinerama /home/sfortas/pix/highway_by_axiomdesign-d9em9fs.jpg

setxkbmap -option compose:ralt
#${HOME}/bin/bar &
# 3 screens:
# /usr/bin/polybar west -r > $HOME/.polybar.west.log 2>&1 & 
/usr/bin/polybar one_screen_left -r  & 
/usr/bin/polybar one_screen_right -r  & 
/usr/bin/polybar one_screen -r  & 
#/usr/bin/polybar east_left -r > $HOME/.polybar.east_left.log 2>&1 &
#/usr/bin/polybar east -r > $HOME/.polybar.east.log 2>&1 &
#/usr/bin/polybar east_right -r > $HOME/.polybar.east_right.log 2>&1 &
picom > $HOME/.compton.log 2>&1 &

bg=$(xrdb -query | awk '/^\*.background:/ { print $2 }')
brmagenta=$(xrdb -query | awk '/^\*.color13:/ { print $2 }')
brred=$(xrdb -query | awk '/^\*.color9:/ { print $2 }')

if xrandr | grep -q " connected 3840x"; then
  single_monitor=yes
fi
# if [[ $single_monitor != "yes" ]]; then
#   bspc monitor DP-2 -n DP-2
# fi
bspc monitor DP-0 -n DP-0
bspc monitor DP-2 -n DP-2

# bspc monitor DP-0   -d W1 W2 W3 
# if [[ $single_monitor != "yes" ]]; then
  # bspc monitor DP-4   -d I II III IV V
  # bspc monitor DP-2   -d VI VII VIII IX X
# else
bspc monitor DP-0   -d I
bspc monitor DP-2   -d II III IV V VI VII VIII IX X
# fi

bspc config border_width         2
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color  $bg
bspc config active_border_color  $brmagenta
bspc config focused_border_color  $brred
bspc config presel_feedback_color  $bg

bspc config top_padding 10
bspc config bottom_padding 10
bspc config right_padding 7
bspc config left_padding 7

bspc config external_rules_command $HOME/bin/bspwm_external_rules

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
